apiVersion: release/v1
kind: Release
metadata:
  name: bat
  web: https://github.com/sharkdp/bat
spec:
  repo:
    type: github
    name: bat
    owner: sharkdp
  file:
    url: https://github.com/sharkdp/bat/releases/download/{{ .Version }}
    src: bat-{{ .Version }}-{{ .Arch }}-{{ .Os }}.tar.gz
    binaryPath: "bat-{{ .Version }}-{{ .Arch }}-{{ .Os }}"
    binary: bat
    mode: archive
  checksum:
    check: false
    url: https://github.com/sharkdp/bat/releases/download/{{ .Version }}
    file: checksums.txt
    format: sha256
  available:
    os:
      linux: unknown-linux-gnu
      darwin: apple-darwin
    arch:
      amd64: x86_64
