apiVersion: release/v1
kind: Release
metadata:
  name: dive
  web: https://github.com/wagoodman/dive
spec:
  repo:
    type: github
    owner: wagoodman
    name: dive
  file:
    url: https://github.com/wagoodman/dive/releases/download/{{ .Version }}
    src: dive_{{ trimPrefix "v" .Version }}_{{ .Os }}_{{ .Arch }}.tar.gz
    binaryPath: "."
    binary: dive
    mode: archive
  checksum:
    check: true
    url: https://github.com/wagoodman/dive/releases/download/{{ .Version }}
    file: dive_{{ trimPrefix "v" .Version }}_checksums.txt
    format: sha256
  available:
    os:
      linux: linux
      darwin: darwin
      windows: windows
    arch:
      amd64: amd64
      arm64: arm64
