apiVersion: release/v1
kind: Release
metadata:
  name: eksctl
  web: https://eksctl.io/
spec:
  url: https://github.com/weaveworks/eksctl/releases/download/{{ .Version }}
  file:
    archive: eksctl_{{ .Os }}_{{ .Arch }}.tar.gz
    binaryPath: "."
    binary: eksctl
    dstbinary: eksctl
  checksum:
    url: https://github.com/weaveworks/eksctl/releases/download/{{ .Version }}
    file: eksctl_checksums.txt
    format: sha256
  available:
    os:
      linux: linux
    arch:
      amd64: amd64
