apiVersion: release/v1
kind: Release
metadata:
  name: gitcomm
  web: https://github.com/karantin2020/gitcomm
spec:
  repo:
    type: github
    name: gitcomm
    owner: karantin2020
  file:
    url: https://github.com/karantin2020/gitcomm/releases/download/{{ .Version }}
    src: gitcomm_{{ .Os }}_{{ .Arch }}
    binaryPath: "."
    binary: gitcomm
    mode: file
  checksum: {}
  available:
    os:
      linux: linux
      darwin: darwin
      windows: windows
    arch:
      amd64: amd64
      i386: "386"
      arm64: arm64
