apiVersion: release/v1
kind: Release
metadata:
  name: golangci-lint
  web: https://golangci-lint.run
spec:
  repo:
    type: github
    name: golangci-lint
    owner: golangci
  file:
    url: https://github.com/golangci/golangci-lint/releases/download/{{ .Version }}
    src: golangci-lint-{{ trimPrefix "v" .Version }}-{{ .Os }}-{{ .Arch }}.tar.gz
    binaryPath: golangci-lint-{{ trimPrefix "v" .Version }}-{{ .Os }}-{{ .Arch }}
    binary: golangci-lint
    mode: archive
  checksum:
    check: true
    url: https://github.com/golangci/golangci-lint/releases/download/{{ .Version }}
    file: golangci-lint-{{ trimPrefix "v" .Version }}-checksums.txt
    format: sha256
  available:
    os:
      linux: linux
      darwin: darwin
    arch:
      amd64: amd64
      arm64: arm64
