apiVersion: release/v1
kind: Release
metadata:
  name: goreleaser
  web: https://goreleaser.com/
spec:
  repo:
    type: github
    name: goreleaser
    owner: goreleaser
  file:
    url: https://github.com/goreleaser/goreleaser/releases/download/{{ .Version }}
    src: goreleaser_{{ .Os }}_{{ .Arch }}.tar.gz
    binaryPath: "."
    binary: goreleaser
    mode: archive
  checksum:
    check: true
    url: https://github.com/goreleaser/goreleaser/releases/download/{{ .Version }}
    file: checksums.txt
    format: sha256
  available:
    os:
      linux: Linux
      darwin: Darwin
      windows: Windows
    arch:
      amd64: x86_64
      i386: i386
      arm64: arm64
