apiVersion: release/v1
kind: Release
metadata:
  name: gptscript
  web: https://gptscript.ai/
spec:
  repo:
    type: github
    name: gptscript
    owner: gptscript-ai
  file:
    url: https://github.com/gptscript-ai/gptscript/releases/download/{{ .Version }}
    src: gptscript-{{ .Version }}-{{ .Os }}-{{ .Arch }}.tar.gz
    binaryPath: "."
    binary: gptscript
    mode: archive
  checksum:
    check: true
    url: https://github.com/cilium/cilium-cli/releases/download/{{ .Version }}
    file: checksums.txt
    format: sha256
  available:
    os:
      linux: linux
      darwin: darwin
    arch:
      amd64: amd64
      arm64: arm64
