apiVersion: release/v1
kind: Release
metadata:
  name: helm
  web: https://helm.sh/
spec:
  repo:
    type: github
    name: helm
    owner: helm
  file:
    url: https://get.helm.sh
    src: helm-{{ .Version }}-{{ .Os }}-{{ .Arch }}.tar.gz
    binaryPath: "{{ .Os }}-{{ .Arch }}"
    binary: helm
    mode: archive
  checksum:
    url: https://get.helm.sh
    file: helm-{{ .Version }}-{{ .Os }}-{{ .Arch }}.tar.gz.sha256sum
    format: sha256
  available:
    os:
      linux: linux
    arch:
      amd64: amd64
