apiVersion: release/v1
kind: Release
metadata:
  name: kubectl
  web: https://github.com/kubernetes/kubectl
spec:
  repo:
    type: github
    name: kubernetes
    owner: kubernetes
  file:
    url: https://dl.k8s.io/release/{{ .Version }}/bin/{{ .Os }}/{{ .Arch }}
    src: kubectl
    binaryPath: "."
    binary: kubectl
    mode: file
  checksum:
    check: false
    url: ""
    file: checksums.txt
    format: sha256
  available:
    os:
      linux: linux
      darwin: darwin
    arch:
      amd64: amd64
      arm64: arm64
