apiVersion: release/v1
kind: Release
metadata:
  name: snyk
  web: https://github.com/snyk/snyk
spec:
  repo:
    type: github
    owner: snyk
    name: snyk
  file:
    url: https://github.com/snyk/snyk/releases/download/{{ .Version }}
    src: snyk-{{ .OS }}
    binaryPath: "."
    binary: snyk
    mode: file
  checksum:
    check: true
    url: https://github.com/snyk/snyk/releases/download/{{ .Version }}
    file: snyk-{{ .OS }}.sha256
    format: sha256
  available:
    os:
      linux: linux
      darwin: macos
      windows: win
    arch:
      amd64: amd64
      arm64: arm64
