on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Release
jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Archive definitions
        run: |
          tar czvf ri-releases-definitions.tar.gz *.yaml
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Current Build"
          files: |
            ri-releases-definitions.tar.gz
